// <auto-generated />
using System;
using ChronoPlan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChronoPlan.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChronoPlan.Domain.Entities.Appointment", b =>
                {
                    b.Property<string>("AppointmentId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CalendarId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("CalendarId");

                    b.ToTable("Appointments", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ChronoPlan.Domain.Entities.AppointmentParticipant", b =>
                {
                    b.Property<string>("AppointmentId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AppointmentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AppointmentParticipants", (string)null);
                });

            modelBuilder.Entity("ChronoPlan.Domain.Entities.Calendar", b =>
                {
                    b.Property<string>("CalendarId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CalendarId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Calendars", (string)null);
                });

            modelBuilder.Entity("ChronoPlan.Domain.Entities.Reminder", b =>
                {
                    b.Property<string>("ReminderId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AppointmentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ReminderTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReminderId");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Reminders", (string)null);
                });

            modelBuilder.Entity("ChronoPlan.Domain.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("RegisterOtpExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisterOtpHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetOtpExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetOtpHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ChronoPlan.Domain.Entities.GroupMeeting", b =>
                {
                    b.HasBaseType("ChronoPlan.Domain.Entities.Appointment");

                    b.ToTable("GroupMeetings", (string)null);
                });

            modelBuilder.Entity("ChronoPlan.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("ChronoPlan.Domain.Entities.Calendar", "Calendar")
                        .WithMany("Appointments")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("ChronoPlan.Domain.Entities.AppointmentParticipant", b =>
                {
                    b.HasOne("ChronoPlan.Domain.Entities.GroupMeeting", "GroupMeeting")
                        .WithMany("Participants")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChronoPlan.Domain.Entities.User", "User")
                        .WithMany("AppointmentParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GroupMeeting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChronoPlan.Domain.Entities.Calendar", b =>
                {
                    b.HasOne("ChronoPlan.Domain.Entities.User", "User")
                        .WithOne("Calendar")
                        .HasForeignKey("ChronoPlan.Domain.Entities.Calendar", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChronoPlan.Domain.Entities.Reminder", b =>
                {
                    b.HasOne("ChronoPlan.Domain.Entities.Appointment", "Appointment")
                        .WithMany("Reminders")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("ChronoPlan.Domain.Entities.GroupMeeting", b =>
                {
                    b.HasOne("ChronoPlan.Domain.Entities.Appointment", null)
                        .WithOne()
                        .HasForeignKey("ChronoPlan.Domain.Entities.GroupMeeting", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChronoPlan.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("ChronoPlan.Domain.Entities.Calendar", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ChronoPlan.Domain.Entities.User", b =>
                {
                    b.Navigation("AppointmentParticipants");

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("ChronoPlan.Domain.Entities.GroupMeeting", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
